steps:
- name: tarampampam/node:14.15-alpine
  entrypoint: sh
  dir: /workspace
  args:
    - -c
    - ./deploy-prod.sh $$NPM_TOKEN "$$GIT_SSH_KEY"
  secretEnv: ['NPM_TOKEN', 'GIT_SSH_KEY']
- name: gcr.io/cloud-builders/gcloud
  entrypoint: bash
  dir: /workspace
  args:
    - -c
    - |
      cd lib && grep version package.json | cut -c15-19 | gcloud secrets versions add forms-version --data-file=-
      echo "0" | gcloud secrets versions add forms-version-alpha --data-file=-
availableSecrets:
  secretManager:
    - versionName: projects/18279890124/secrets/npm-access-key/versions/latest
      env: 'NPM_TOKEN'
    - versionName: projects/18279890124/secrets/git-ssh-key/versions/latest
      env: 'GIT_SSH_KEY'
