/**
 * A group of symbols in the API tab of a showcase page
 */
export interface ShowcaseApiSection {
  title: string;
  /** One sentence below the title: what the symbols are for */
  description?: string;
  /** Exported names from `@lab900/forms`, in the order to show them */
  symbols: string[];
  /**
   * For the field models of the `Lab900FormField` union. The API tab then shows a schema snippet per field
   * and renders its options interface (the type of the `options` property) inline, because that interface
   * is where the configuration of the field lives.
   */
  fieldUsage?: boolean;
}

/**
 * The file that `scripts/generate-api-docs.mjs` writes.
 * Generated by `npm run docs:api`, served from `assets/api/api.json`.
 */
export interface ApiDocs {
  symbols: Record<string, ApiSymbol>;
}

export interface ApiSymbol {
  name: string;
  kind: 'component' | 'directive' | 'interface' | 'type' | 'enum';
  typeParameters?: string;
  /** Path in the repository, with the line */
  source: string;
  description?: string;
  example?: string;
  deprecated?: string | true;
  selector?: string;
  abstract?: boolean;
  extends?: string[];
  /** The type of a type alias, or the members of an enum */
  type?: string;
  members?: ApiMember[];
}

export interface ApiMember {
  name: string;
  /** Only set on component and directive members */
  kind?: 'input' | 'model' | 'output';
  type: string;
  required?: boolean;
  optional?: boolean;
  default?: string;
  /** `signal`: a value, a function of the data, or a signal. `function`: a value or a function of the data. */
  reactive?: 'signal' | 'function';
  inheritedFrom?: string;
  description?: string;
  example?: string;
  deprecated?: string | true;
}
